# Generated by Django 3.2.18 on 2023-03-28 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_plan', models.CharField(choices=[('basic', 'A link to a thumbnail that is 200px in height'), ('premium', 'A link to a thumbnail that is 200px, 400px in height and a link to the originally uploaded image'), ('enterprise', 'A link to a thumbnail that is 200px, 400px in height and a link to the originally uploaded image. Ability to fetch a link for a previously uploaded image that expires after a number of seconds (user can specify any number between 300 and 30000)')], max_length=11)),
                ('image_pixel_size', models.PositiveIntegerField(default=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='uplaod_images')),
                ('url', models.URLField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
